Repository SAP/ai-sdk-java, pull requests merged in 2024-10, with the labels that each got.

#64 Added release script
  .github/actions/pr-is-mergeable/action.yaml
  .github/actions/workflow-succeeded/action.yaml
  .github/workflows/perform-release.yml
  .github/workflows/prepare-release.yaml
  .pipeline/scripts/get-release-versions.py
  .pipeline/scripts/set-release-versions.py
  core/pom.xml
  foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/model/OpenAiCompletionParameters.java
  orchestration/pom.xml
  pom.xml
  sample-code/spring-app/pom.xml
Labels: please review

#70 Update OpenAI test payload
  foundation-models/openai/src/test/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiClientTest.java
  foundation-models/openai/src/test/resources/chatCompletionResponse.json
Labels: please review

#81 Notify when main branch fails
  .github/workflows/continuous-integration.yaml
Labels: please review

#52 Added Orchestration Data Masking tests
  README.md
  foundation-models/openai/src/test/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiClientTest.java
  foundation-models/openai/src/test/resources/__files/chatCompletionResponse.json
  foundation-models/openai/src/test/resources/__files/embeddingResponse.json
  orchestration/src/test/java/com/sap/ai/sdk/orchestration/client/OrchestrationUnitTest.java
  orchestration/src/test/resources/__files/filteringLooseResponse.json
  orchestration/src/test/resources/__files/maskingResponse.json
  orchestration/src/test/resources/__files/templatingResponse.json
  orchestration/src/test/resources/maskingRequest.json
  sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/OrchestrationController.java
  sample-code/spring-app/src/main/resources/static/index.html
  sample-code/spring-app/src/test/java/com/sap/ai/sdk/app/controllers/OrchestrationTest.java
Labels: please review

#91 Dependabot Auto-Merge fix
  .github/workflows/continuous-integration.yaml
  .github/workflows/dependabot-automerge.yaml
Labels: please review

#92 Refactor docs
  CONTRIBUTING.md
  README.md
  docs/guides/AI_CORE_DEPLOYMENT.md
  docs/guides/OPENAI_CHAT_COMPLETION.md
  docs/guides/ORCHESTRATION_CHAT_COMPLETION.md
Labels: please review

#98 Fix release
  core/pom.xml
  foundation-models/openai/pom.xml
  orchestration/pom.xml
  pom.xml
  sample-code/spring-app/pom.xml
Labels: please review

#53 Added deployment cache
  core/src/main/java/com/sap/ai/sdk/core/AiCoreDeployment.java
  core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java
  core/src/main/java/com/sap/ai/sdk/core/DeploymentCache.java
  core/src/test/java/com/sap/ai/sdk/core/CacheTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/WireMockTestServer.java
  sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/Application.java
  sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/ConfigurationController.java
  sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/DeploymentController.java
  sample-code/spring-app/src/main/java/com/sap/ai/sdk/app/controllers/ScenarioController.java
  sample-code/spring-app/src/main/resources/static/index.html
Labels: please review

#102 Update docs
  README.md
  docs/adrs/004-core-class-for-service-integration.md
  docs/guides/AI_CORE_DEPLOYMENT.md
Labels: please review

#103 Added resource group isolation to DeploymentCache
  core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java
  core/src/main/java/com/sap/ai/sdk/core/DeploymentCache.java
  core/src/test/java/com/sap/ai/sdk/core/CacheTest.java
  core/src/test/resources/__files/GPT4DeploymentResponse.json
  core/src/test/resources/__files/emptyDeploymentResponse.json
Labels: please review

#112 Update OPENAI_CHAT_COMPLETION.md
  docs/guides/OPENAI_CHAT_COMPLETION.md
Labels: documentation, please review

#106 Run PMD by default
  pom.xml
Labels: please review

#109 Run Spotbugs by default
  pom.xml
Labels: please review

#111 Run Checkstyle by default
  .pipeline/checkstyle-suppressions.xml
  .pipeline/config.yml
  pom.xml
Labels: please review

#104 Lombok use of `val`
  .pipeline/sdk_specific_pmd_rules.xml
  core/src/main/java/com/sap/ai/sdk/core/AiCoreDestination.java
  core/src/main/java/com/sap/ai/sdk/core/AiCoreService.java
  core/src/main/java/com/sap/ai/sdk/core/DeploymentCache.java
  core/src/main/java/com/sap/ai/sdk/core/DestinationResolver.java
  core/src/test/java/com/sap/ai/sdk/core/AiCoreServiceTest.java
  core/src/test/java/com/sap/ai/sdk/core/CacheTest.java
  core/src/test/java/com/sap/ai/sdk/core/DestinationResolverTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/ArtifactUnitTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/ConfigurationUnitTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/DeploymentUnitTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/ExecutionUnitTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/ScenarioUnitTest.java
  core/src/test/java/com/sap/ai/sdk/core/client/WireMockTestServer.java
Labels: please review

#125 Chore/sample app readme update
  sample-code/spring-app/README.md
Labels: please-review

#49 [Streaming] Fix issues when not using `try-with-resource`
  foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/IterableStreamConverter.java
  foundation-models/openai/src/main/java/com/sap/ai/sdk/foundationmodels/openai/OpenAiStreamingHandler.java
  foundation-models/openai/src/test/java/com/sap/ai/sdk/foundationmodels/openai/IterableStreamConverterTest.java
Labels: please-review
